services:
  - type: web
    name: api-finance
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: apiFinance
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromSecret: app-url

      # --- DATABASE CONFIGURATION ---
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: api-finance-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: api-finance-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: api-finance-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: api-finance-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: api-finance-db
          property: password

      # --- LARAVEL SETTINGS ---
      - key: LOG_CHANNEL
        value: stack
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file

      # --- MAIL ---
      - key: MAIL_MAILER
        value: log

      # --- CUSTOM SETTINGS ---
      - key: RUN_MIGRATIONS
        value: true
      - key: SEED_DB
        value: true

      # --- SECOND DATABASE (Render2) ---
      - key: RENDER2_DB_HOST
        value: dpg-d435s8uuk2gs738oqp20-a
      - key: RENDER2_DB_DATABASE
        value: apifinance
      - key: RENDER2_DB_USERNAME
        value: apifinance_user
      - key: RENDER2_DB_PASSWORD
        value: FBURK2fnqStM5e2XbXQcGztCCH63tU2D
      - key: RENDER2_DB_PORT
        value: 5432

databases:
  - name: api-finance-db
    databaseName: apifinancedb
    user: apifinancedb_user
    plan: starter
